title: Template
author: Books CEG
logo: figures/TUDelft_logo_rgb.png
copyright: Delft University of Technology, CC BY 4.0 # overriden by extra footer/sphinx config

execute:
  execute_notebooks: "off"

only_build_toc_files: true

html:
  comments:
    hypothesis: true
  use_multitoc_numbering: false

sphinx:
  config:
    html_show_copyright: true
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_theme_options:
      repository_url: https://github.com/Tom-van-Woudenberg/Computational-science
      use_repository_button: true
      launch_buttons:
        thebe: true
  extra_extensions:
    - sphinx.ext.imgconverter
    - download_link_replacer
    - jupyterbook_patches

bibtex_bibfiles: 
  - references.bib
